login_page_url = "https://adzwedo.getpinner.com/user/signin"
correct_username = "kate+eff@effortis.com"
incorrect_username = "incorrect+uname@effortis.com"
correct_pwd = "123456"
random_pwd = "rnd12pwd$"
profile_name = "Test test"
